#!/usr/bin/env bash

set -euo pipefail

PACKAGES=(
    fd
    jq
    zsh
    git
    bat
    fzf
    nvim
    tmux
    ripgrep
    starship
)

sudo apt-get update -qq && sudo apt install "$PACKAGES[@]"

sudo ln -sf /usr/bin/fdfind /usr/local/bin/fd

echo "Setup script finished successfully"

export XDG_CONFIG_HOME="$HOME/.config"
mkdir -p "$XDG_CONFIG_HOME"

echo "Setting up configurations..."

PWD=$(pwd)

echo "Linking NeoVim config"
ln -sfn "$PWD/nvim" "$HOME/.config/nvim"

echo "Linking Tmux config and install the package manager"
ln -sfn "$PWD/.tmux.conf" "$HOME/.tmux.conf"

if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

echo "Linking Starship terminal prompt line"
ln -sfn "$PWD/starship.toml" "$HOME/.config/starship.toml"

echo "Linking Zsh dotfile and install plugins"
ln -sfn "$PWD/.zshrc" "$HOME/.zshrc"

mkdir -p "$HOME/.zsh"
git clone https://github.com/zsh-users/zsh-completions.git ~/.zsh/zsh-completions
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.zsh/zsh-syntax-highlighting

source ~/.zshrc

echo "=== Dotfiles setup finished successfully ==="
